jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Restore cached dependencies
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c
      with:
        key: ${{ runner.os }}_spark_2.4_hadoop_2.7
        path: '# /var/cache/apt/archives/*.deb

          ~/.m2/repository

          ~/opt

          '
        restore-keys: '${{ runner.os }}-

          '
    - continue-on-error: true
      name: Cluster spark_2.4_hadoop_2.7_hive_0.14
      run: '${{github.workspace}}/actions/build_and_run_all_spark_2.4_hadoop_2.7_hive_0.14_part_1.sh

        '
name: HiBench CI SPARK_2.4_HADOOP_2.7
on:
  repository_dispatch:
    types: trigger-ga___hibench_ci_spark2.4_hadoop_2.7_part_1.yml
permissions:
  contents: read
